#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 29 12:16:09 2020

@author: femw90
"""

"""
Created on Tue Oct 27 15:22:35 2020

@author: femw90
"""

'''
Problem 3
'''

import numpy as np
import matplotlib.pyplot as plt
import math
